staging:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.10.0
    - dpl --provider=heroku --app=tural-blogged --api_key=$HEROKU_STAGING_API_KEY
  only:
    - main